# Generated by Django 4.2.1 on 2023-05-08 03:27

import Aplicaciones.Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('codigo', models.CharField(default=Aplicaciones.Usuarios.models.numeroRandom, max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('identificacion', models.PositiveIntegerField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('tipoUsuario', models.CharField(choices=[('A', 'Administrador'), ('V', 'Vendedor')], max_length=1)),
            ],
        ),
    ]
